# Generated by Django 3.0.7 on 2020-08-28 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extuser',
            name='category',
        ),
    ]
