# Generated by Django 3.0.7 on 2020-08-29 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='teamdescription',
        ),
        migrations.CreateModel(
            name='TeamDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamdescription', models.TextField()),
                ('teammotive', models.TextField()),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Details.Teams')),
            ],
        ),
    ]
