# Generated by Django 3.0.7 on 2020-09-10 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Details', '0002_auto_20200829_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urteam', to='Details.Teams')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uruser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trteam', to='Details.Teams')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
